{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "277cd597-aeba-47b1-bd81-ea03af8fde5b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Range (nautical miles): 3000.00\n",
      "Endurance (hours): 20.00\n",
      "Total Weight (lbs): 11000.00\n",
      "CG Position (ft): 8.33\n",
      "Lift (N): 183750.00\n",
      "Drag (N): 2450.00\n",
      "Weight (N): 49050.00\n",
      "Acceleration (m/s²): 2.00\n",
      "Velocity (m/s): 70.00\n",
      "Distance (m): 700.00\n"
     ]
    }
   ],
   "source": [
    "def calculate_range(fuel_capacity, fuel_consumption_rate, true_air_speed):\n",
    "    range_in_hours = fuel_capacity / fuel_consumption_rate\n",
    "    range_in_miles = range_in_hours * true_air_speed\n",
    "    return range_in_miles\n",
    "\n",
    "def calculate_endurance(fuel_capacity, fuel_consumption_rate):\n",
    "    endurance_in_hours = fuel_capacity / fuel_consumption_rate\n",
    "    return endurance_in_hours\n",
    "\n",
    "def calculate_total_weight(payload, fuel_weight):\n",
    "    return payload + fuel_weight\n",
    "\n",
    "def calculate_cg_position(moment_list, total_weight):\n",
    "    total_moment = sum(moment_list)\n",
    "    cg_position = total_moment / total_weight\n",
    "    return cg_position\n",
    "\n",
    "def calculate_moment(weight, arm):\n",
    "    return weight * arm\n",
    "\n",
    "def calculate_lift(cl, rho, v, s):\n",
    "    return 0.5 * cl * rho * v**2 * s\n",
    "\n",
    "def calculate_drag(cd, rho, v, s):\n",
    "    return 0.5 * cd * rho * v**2 * s\n",
    "\n",
    "def calculate_weight(mass, g):\n",
    "    return mass * g\n",
    "\n",
    "def calculate_acceleration(thrust, drag, weight, mass):\n",
    "    return (thrust - drag - weight) / mass\n",
    "\n",
    "def calculate_velocity(velocity, acceleration, time):\n",
    "    return velocity + acceleration * time\n",
    "\n",
    "def calculate_distance(velocity, time):\n",
    "    return velocity * time\n",
    "\n",
    "def pretty_print(*args):\n",
    "    labels = [\n",
    "        \"Range (nautical miles)\", \"Endurance (hours)\", \"Total Weight (lbs)\",\n",
    "        \"CG Position (ft)\", \"Lift (N)\", \"Drag (N)\", \"Weight (N)\",\n",
    "        \"Acceleration (m/s²)\", \"Velocity (m/s)\", \"Distance (m)\"\n",
    "    ]\n",
    "    for label, value in zip(labels, args):\n",
    "        print(f\"{label}: {value:.2f}\")\n",
    "\n",
    "\n",
    "# === Input Data ===\n",
    "fuel_capacity = 1000  # gallons\n",
    "fuel_consumption_rate = 50  # gallons per hour\n",
    "true_air_speed = 150  # knots\n",
    "\n",
    "payload = 5000  # pounds\n",
    "fuel_weight = 6000  # pounds\n",
    "\n",
    "moment_list = [10000, 2500]  # pound-feet\n",
    "total_weight = 1500  # pounds  (used for CG)\n",
    "\n",
    "cl = 1.5  # lift coefficient\n",
    "rho = 1.225  # air density (kg/m³)\n",
    "v = 100  # m/s\n",
    "s = 20  # m²\n",
    "\n",
    "cd = 0.02  # drag coefficient\n",
    "mass = 5000  # kg\n",
    "g = 9.81  # m/s²\n",
    "\n",
    "thrust = 6000  # N\n",
    "drag = 5000  # N\n",
    "velocity = 50  # initial velocity in m/s\n",
    "acceleration = 2  # m/s²\n",
    "time = 10  # seconds\n",
    "\n",
    "\n",
    "# === Calculations ===\n",
    "range_ = calculate_range(fuel_capacity, fuel_consumption_rate, true_air_speed)\n",
    "endurance = calculate_endurance(fuel_capacity, fuel_consumption_rate)\n",
    "total_weight_lb = calculate_total_weight(payload, fuel_weight)\n",
    "cg_position = calculate_cg_position(moment_list, total_weight)\n",
    "lift = calculate_lift(cl, rho, v, s)\n",
    "drag_force = calculate_drag(cd, rho, v, s)\n",
    "weight_newton = calculate_weight(mass, g)\n",
    "new_velocity = calculate_velocity(velocity, acceleration, time)\n",
    "distance = calculate_distance(new_velocity, time)\n",
    "\n",
    "# === Output ===\n",
    "pretty_print(range_, endurance, total_weight_lb, cg_position, lift, drag_force, weight_newton, acceleration, new_velocity, distance)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "f1c63ba0-8785-4caa-9f94-2e5faa605cda",
   "metadata": {},
   "outputs": [],
   "source": [
    "def save_info_to_file(range_, endurance, total_weight, cg_position, lift, drag, weight, acceleration, velocity, distance, file):\n",
    "    file.write(\"Performance Calculations:\\n\")\n",
    "    file.write(\"Range: {} miles\\n\".format(range_))\n",
    "    file.write(\"Endurance: {} hours\\n\".format(endurance))\n",
    "    file.write(\"Total Weight: {} lbs\\n\".format(total_weight))\n",
    "    file.write(\"Center of Gravity Position: {} feet\\n\".format(cg_position))\n",
    "    file.write(\"Lift: {} Newtons\\n\".format(lift))\n",
    "    file.write(\"Drag: {} Newtons\\n\".format(drag))\n",
    "    file.write(\"Weight: {} Newtons\\n\".format(weight))\n",
    "    file.write(\"Acceleration: {} m/s^2\\n\".format(acceleration))\n",
    "    file.write(\"Velocity: {} m/s\\n\".format(velocity))\n",
    "    file.write(\"Distance: {} meters\\n\".format(distance))\n",
    "\n",
    "# Save to file\n",
    "with open(\"aircraft_performance_analysis.txt\", \"w\") as f: \n",
    "    save_info_to_file(range_, endurance, total_weight_lb, cg_position, lift, drag_force, weight_newton, acceleration, new_velocity, distance, file=f)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5eea09ac-f824-470d-a6b2-ebed6f651ec7",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
